//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF1
{
    using System;
    
    public partial class GetByIdArea_Result1
    {
        public int IdDepartamento { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Nombre1 { get; set; }
    }
}
